version: '3.3'

services:
  bind-dns:
    image: patklaey/bind-dns:0.2
    container_name: bind-dns
    restart: always
    network_mode: "host"
    volumes:
      - ./db.patklaey.ch:/etc/bind/zones/db.patklaey.ch
      - ./named.conf:/etc/bind/named.conf
      
